# Generated by Django 5.0.1 on 2024-03-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('phoneNumber', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=235)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('client', 'Client')], max_length=10)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=23)),
            ],
        ),
    ]
