# Generated by Django 5.0.1 on 2024-03-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venueName', models.CharField(max_length=23)),
                ('address', models.CharField(max_length=23)),
                ('latitude', models.CharField(max_length=23)),
                ('longitude', models.CharField(max_length=23)),
                ('venueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
    ]
