# Generated by Django 5.0.1 on 2024-03-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('venue', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('beginTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('hours', models.IntegerField()),
                ('bookingTime', models.DateField()),
                ('totalPrice', models.IntegerField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=23)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employeelist')),
                ('venueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
    ]
