# Generated by Django 5.0.1 on 2024-03-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pymId', models.AutoField(primary_key=True, serialize=False)),
                ('pymtTime', models.DateField()),
                ('phone', models.IntegerField()),
                ('solde', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bankApp', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=23)),
                ('image', models.ImageField(upload_to='paymt_images/')),
                ('bookinId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
